#name: Linter
#on: [push]
#jobs:
#  linter:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Run Scalastyle Linter
#        run: |
#          sbt +scalastyle
#          sbt +test:scalastyle
